Moved err output to stderr
Signed-off-by: Nedwardo <edwardbo123@gmail.com>

diff --git a/aliases/.aliases/update_stow b/aliases/.aliases/update_stow
--- a/aliases/.aliases/update_stow
+++ b/aliases/.aliases/update_stow
@@ -1,14 +1,14 @@
 update_stow(){
 	set -e
 	if [ $# -eq 0 ]; then
-		echo "Need at least one argument"
+		>&2 echo "Need at least one argument"
 		exit -1
 	fi
 
 	(
 		cd $HOME/dotfiles
 		for arg in $@; do
-			stow --adopt --target=$HOME $arg && echo "Successfully updated stow for $arg" || { echo "Could not update stow for $arg"; exit -1; }
+			stow --adopt --target=$HOME $arg && echo "Successfully updated stow for $arg" || { >&2 echo "Could not update stow for $arg"; exit -1; }
 		done
 	)
 	exec $SHELL
